### ISSUE TITLE
docker-compose.yml里面prometheus.yml挂载错目录了

### ISSUE THREAD

**Issue by ren-jimmy** [nivin-studio/go-zero-mall#1]
./prometheus/prometheus.yml:/opt/bitnami/prometheus-operator/conf/prometheus.yml

这个才对

**Comment by nivin-studio** [comment]
https://hub.docker.com/r/bitnami/prometheus

可以参考下这个

**Comment by nivin-studio** [comment]
> ./prometheus/prometheus.yml:/opt/bitnami/prometheus-operator/conf/prometheus.yml
> 
> 这个才对

可以参考下这个 https://hub.docker.com/r/bitnami/prometheus
